---
- name: Ensure php packages are installed
  apt: name={{item}} state=installed
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-xmlrpc
    - libapache2-mod-php5

- name: Ensure apache mod is enabled
  file:
    src: /etc/apache2/mods-available/{{ item }}
    dest: /etc/apache2/mods-enabled/{{ item }}
    state: link
  with_items:
    - php5.conf
    - php5.load
  notify: Restart apache

- name: Setup php.ini
  template: src=../templates/php.ini.j2 dest=/etc/php5/apache2/php.ini
  notify: Restart apache

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags:
    - composer

- name: Rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags:
    - composer

- name: Make composer executable
  file: path=/usr/local/bin/composer mode=0755
  tags:
    - composer
